/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package management;


import dao.ProductDAO;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import management.ProductModel;
import management.ItemCard;
import management.Cart;
import management.CartItem;
import com.google.zxing.BarcodeFormat;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.MatrixToImageWriter;
import com.google.zxing.common.BitMatrix;
import com.google.zxing.qrcode.QRCodeWriter;



/**
 *
 * @author ACER
 */
public class Items extends javax.swing.JPanel {
     private List<ProductModel> allProducts = new ArrayList<>();
    private Cart cart = new Cart();

    public Items() {
        initComponents(); // dùng component của NetBeans
        // thiết lập layout và size cho contentPanel
        contentPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 20, 20));
        contentPanel.setPreferredSize(new Dimension(800, 1000));

        // load sản phẩm
        loadProducts();
        addSearchEvent();
    }

    private void loadProducts() {
        allProducts = ProductDAO.getAllProducts();
        showProducts(allProducts);
    }

    private void showProducts(List<ProductModel> list) {
        contentPanel.removeAll();
        for (ProductModel p : list) {
            contentPanel.add(new ItemCard(p, cart)); // sử dụng ItemCard có Cart
        }
        contentPanel.revalidate();
        contentPanel.repaint();
    }

    private void addSearchEvent() {
        txtSearch.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            public void insertUpdate(javax.swing.event.DocumentEvent e) { search(); }
            public void removeUpdate(javax.swing.event.DocumentEvent e) { search(); }
            public void changedUpdate(javax.swing.event.DocumentEvent e) { search(); }
        });
    }

    private void search() {
        String key = txtSearch.getText().toLowerCase();
        List<ProductModel> result = new ArrayList<>();
        for (ProductModel p : allProducts) {
            if (p.getName().toLowerCase().contains(key)) {
                result.add(p);
            }
        }
        showProducts(result);
    }

   private void showCartWithQRAndImage() {
        // 1. Chuỗi thanh toán demo (sửa cho ngân hàng thật)
        String paymentInfo = "STK:123456789\nTổng tiền: " + cart.getTotal() + " đ\nNgười nhận: ABC Bank";

     

        // 3. Hiển thị danh sách sản phẩm trong giỏ
        StringBuilder sb = new StringBuilder();
        for (CartItem item : cart.getItems()) {
            sb.append(item.getProduct().getName())
              .append(" x ").append(item.getQuantity())
              .append(" = ").append(item.getTotalPrice()).append(" đ\n");
        }
        sb.append("\nTổng tiền: ").append(cart.getTotal()).append(" đ");

        JTextArea ta = new JTextArea(sb.toString());
        ta.setEditable(false);
        ta.setBackground(null);

        // 4. Thêm ảnh sản phẩm demo (có thể thay bằng ảnh thật)
        JLabel lbl = new JLabel(new ImageIcon(getClass().getResource("/resources/mbbank.jpg")));
        

        // 5. JPanel hiển thị
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.add(ta);
        panel.add(lbl);
        

        JOptionPane.showMessageDialog(this, panel, "Giỏ hàng & Thanh toán", JOptionPane.PLAIN_MESSAGE);
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();

        jLabel1.setText("Search:");

        jButton1.setText("Cart");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(jButton1)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(jLabel1))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(contentPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    showCartWithQRAndImage();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
