/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package management;

import javax.swing.*;
import javax.swing.SpinnerNumberModel;



/**
 *
 * @author ACER
 */
public class ItemCard extends javax.swing.JPanel {
    private ProductModel product;
    private Cart cart;

    public ItemCard(ProductModel product, Cart cart) {
        this.product = product;
        this.cart = cart;
        initComponents(); // NetBeans tự sinh
        showData();

        // Khởi tạo Spinner sau khi initComponents
        spQty.setModel(new SpinnerNumberModel(1, 1, product.getQuantity(), 1));
    }

    private void showData() {
        lblName.setText(product.getName());
        lblPrice.setText(product.getPrice() + " đ");
        lblStock.setText("Stock: " + product.getQuantity());
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        spQty = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(180, 220));

        lblName.setText("jLabel1");

        lblPrice.setText("jLabel1");

        lblStock.setText("jLabel1");

        btnAdd.setText("Buy");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAdd)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblStock)
                                .addComponent(lblPrice)
                                .addComponent(lblName)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addComponent(spQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblStock)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        int buyQty = (int) spQty.getValue();
        if (buyQty <= 0) {
            JOptionPane.showMessageDialog(this, "Số lượng không hợp lệ");
            return;
        }
        if (buyQty > product.getQuantity()) {
            JOptionPane.showMessageDialog(this, "Không đủ hàng");
            return;
        }

        cart.addItem(product, buyQty);
        product.setQuantity(product.getQuantity() - buyQty);
        lblStock.setText("Stock: " + product.getQuantity());

        JOptionPane.showMessageDialog(this, "Đã thêm vào giỏ hàng!");
        // Cập nhật lại Spinner max value
        spQty.setModel(new SpinnerNumberModel(1, 1, product.getQuantity(), 1));
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblStock;
    private javax.swing.JSpinner spQty;
    // End of variables declaration//GEN-END:variables
}
